---
#
# PLEASE NOTE: Managed workflow - do not change manually
#
name: Scan for secrets

on:
  push:
    branches:
      - "**"

jobs:
  scan-for-secrets:
    name: Scan for secrets
    uses: wetransform/gha-workflows/.github/workflows/scan-for-secrets.yml@704a9e0b4c99f8222648941f051a10dacc770b9f # v4.3.0
    secrets:
      SLACK_EXPOSED_SECRETS_WEBHOOK: ${{ secrets.SLACK_EXPOSED_SECRETS_WEBHOOK }}
